/*
 * SealData.cs — per-launcher compile-time seal, generated by build.sh / the
 * launcher pool. These values are unique to ONE compiled binary and are the
 * keys with which the appended overlay envelope is sealed.
 *
 *   KEY : 32 bytes (64 hex chars)  — AES-256 launcher key (K_L)
 *   IV  : 16 bytes (32 hex chars)  — AES-256 CTR initialization value (IV_L)
 *   TAG : 16 bytes (32 hex chars)  — random nonce: makes every compiled
 *                                    launcher byte-unique (hash diversity)
 */
using System;
class SealData {
    public static String KEY = "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff";
    public static String IV  = "102030405060708090a0b0c0d0e0f1020";
    public static String TAG = "a1b2c3d4e5f60718293a4b5c6d7e8f901";
}